-- Your SQL goes here
CREATE TABLE persona (
    CODIGO SERIAL NOT NULL PRIMARY KEY,
    IDENTIFICACION VARCHAR(20) NOT NULL,
    NOMBRE TEXT NOT NULL,
    GENERO VARCHAR(1),
    ESTADOCIVIL VARCHAR(100),
    FECHANACIMIENTO TEXT,
    TELEFONO VARCHAR(10) NOT NULL,
    DIRECCION TEXT,
    EMAIL TEXT NOT NULL,
    VALIDADO BOOLEAN,
    OBSERVACION TEXT
)